/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/care` | `/care`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/identify` | `/identify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownInputParams; } | { pathname: `/screens/_profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/_sell`; params?: Router.UnknownInputParams; } | { pathname: `/search/filters`; params?: Router.UnknownInputParams; } | { pathname: `/categories/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/features/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plant-details/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/search/[query]`, params: Router.UnknownInputParams & { query: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/care` | `/care`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/identify` | `/identify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/_profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/_sell`; params?: Router.UnknownOutputParams; } | { pathname: `/search/filters`; params?: Router.UnknownOutputParams; } | { pathname: `/categories/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/features/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/plant-details/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/search/[query]`, params: Router.UnknownOutputParams & { query: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/care${`?${string}` | `#${string}` | ''}` | `/care${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/identify${`?${string}` | `#${string}` | ''}` | `/identify${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/message${`?${string}` | `#${string}` | ''}` | `/message${`?${string}` | `#${string}` | ''}` | `/screens/_profile${`?${string}` | `#${string}` | ''}` | `/screens/_sell${`?${string}` | `#${string}` | ''}` | `/search/filters${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/care` | `/care`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/identify` | `/identify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/message` | `/message`; params?: Router.UnknownInputParams; } | { pathname: `/screens/_profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/_sell`; params?: Router.UnknownInputParams; } | { pathname: `/search/filters`; params?: Router.UnknownInputParams; } | `/categories/${Router.SingleRoutePart<T>}` | `/features/${Router.SingleRoutePart<T>}` | `/plant-details/${Router.SingleRoutePart<T>}` | `/search/${Router.SingleRoutePart<T>}` | { pathname: `/categories/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/features/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plant-details/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/search/[query]`, params: Router.UnknownInputParams & { query: string | number; } };
    }
  }
}
